---
title: "Figure S1 Collection Locations"
author: "Talia_Karasov"
date: "5/21/2019"
output: html_document
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=12, fig.height=8, fig.path='Figs/',
                      echo=FALSE, warning=FALSE, message=FALSE)
```

```{r}
library(ggmap)
library(ggsn)
#plot locations of collections


scalebar = function(x,y,w,n,d, units="km"){
  # x,y = lower left coordinate of bar
  # w = width of bar
  # n = number of divisions on bar
  # d = distance along each division
  
  bar = data.frame( 
    xmin = seq(0.0, n*d, by=d) + x,
    xmax = seq(0.0, n*d, by=d) + x + d,
    ymin = y,
    ymax = y+w,
    z = rep(c(1,0),n)[1:(n+1)],
    fill.col = rep(c("black","white"),n)[1:(n+1)])
  
  labs = data.frame(
    xlab = c(seq(0.0, (n+1)*d, by=d) + x, x), 
    ylab = c(rep(y+w*1.5, n+2), y+3*w),
    text = c(as.character(seq(0.0, ((n+1)*d)/1000, by=d/1000)), units)
  )
  list(bar, labs)
}

#germany
locations=read.table("~/Dropbox/germany_pathogen_collections/data_files_rmarkdown/location_sampling_lat_long.txt",header=T)
sb = scalebar(x = 9.05, y = 48.45, w = 0.005, n = 3 , 0.0143, "km" )

pdf("~/Dropbox/germany_pathogen_collections/data_files_rmarkdown/locations_collections.pdf")

#qmplot(Longitude, Latitude, data = locations, extent = "panel", mapcolor = "bw", maptype = "toner")+geom_point(color="RED", cex=4)+geom_rect(data=sb[[1]], aes(xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax, fill=z), inherit.aes=F, show.legend = F,  color = "black", fill = sb[[1]]$fill.col)+geom_text(data=sb[[2]], aes(x=xlab, y=ylab, label=text), inherit.aes=F, show.legend = F) 

#the above code is working poorly
height = max(locations$Latitude) - min(locations$Latitude) 
width = max(locations$Longitude) - min(locations$Longitude)
borders = c(bottom = min(locations$Latitude) - 0.1 * height, 
            top = max(locations$Latitude) + 0.1 * height,
            left = min(locations$Longitude) - 0.1 * width,
            right = max(locations$Longitude) + 0.1 * width)

map = get_stamenmap(borders, zoom = 10, maptype = "toner-lite")
ggmap(map) +
  geom_point(data = locations, mapping = aes(x = Longitude, y = Latitude), color = "RED", cex = 4) +
  geom_rect(data=sb[[1]], aes(xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax, fill=z), inherit.aes=F, show.legend = F,  color = "black", fill = sb[[1]]$fill.col)+geom_text(data=sb[[2]], aes(x=xlab, y=ylab, label=text), inherit.aes=F, show.legend = F) 

dev.off()


dev.off()

#sweden
locations=read.table("~/Dropbox/controlled_metagenomics/Swedish_samples/swedish_sites.txt",header=T, sep="\t")
sb = scalebar(17, 56, 0.5, n = 5, 1, "km" )

pdf("~/Dropbox/controlled_metagenomics/results_figures/swedish_map2.pdf", useDingbats = FALSE)
#qmplot(Longitude, Latitude, data = locations, extent = "panel")+geom_point(color="RED", cex=4)+geom_rect(data=sb[[1]], aes(xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax, fill=z), inherit.aes=F, show.legend = F,  color = "black", fill = sb[[1]]$fill.col)+geom_text(data=sb[[2]], aes(x=xlab, y=ylab, label=text), inherit.aes=F, show.legend = F) 



#the above code is working poorly
height = max(locations$Latitude) - min(locations$Latitude) 
width = max(locations$Longitude) - min(locations$Longitude)
borders = c(bottom = min(locations$Latitude) - 0.1 * height, 
            top = max(locations$Latitude) + 0.1 * height,
            left = min(locations$Longitude) - 0.9 * width,
            right = max(locations$Longitude) + 0.9 * width)

map = get_stamenmap(borders, zoom = 6, maptype = "toner-lite")
hm = get_map(borders, zoom = 6, source = "stamen",
             maptype = "toner") 
ggmap(map, extent = "device") +
  geom_point(data = locations, mapping = aes(x = Longitude, y = Latitude), color = "RED", cex = 4)  +
  theme_bw()

#Scale bar not working well
#+scalebar(data = locations, transform = TRUE, dist_unit = "km", dist = 1)
  
  
  #geom_rect(data=sb[[1]], aes(xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax, fill=z), inherit.aes=F, show.legend = F,  color = "black", fill = sb[[1]]$fill.col)+geom_text(data=sb[[2]], aes(x=xlab, y=ylab, label=text), inherit.aes=F, show.legend = F) 

dev.off()
```
